added 'remote tabke create' to table commands
keboola/developers-docs pull request #299
Opened 2024-04-30 08:34 UTC by hosekpeter

Jira issue(s): [PROOF-204](https://keboola.atlassian.net/browse/PROOF-204)

Changes:

- added `remote table create` to table commands

---

2024-04-30 13:56 UTC, michaljurecko requested changes

2024-04-30 13:56 UTC, michaljurecko commented on cli/commands/remote/table/index.md
> +| [kbc remote table create](/cli/commands/remote/create/table/) | Create a new [table](https://help.keboola.com/storage/tables/). |
1. You moved the file.
2. But the link is not updated.
3. Also `permalink` [file header](https://raw.githubusercontent.com/keboola/developers-docs/1d1b03ed8e7df9bddbce2416c318670ef2ece513/cli/commands/remote/table/create/index.md) is not updated.
4. Navigation/menu update is also missing: https://github.com/keboola/developers-docs/blob/main/_data/navigation.yml

2024-04-30 15:04 UTC, michaljurecko approved these changes
LGTM

2024-05-02 13:08 UTC, hhanova approved these changes

2024-05-02 14:00 UTC, merged